### ISSUE TITLE
useFactory

### ISSUE THREAD

**Issue by ilyamixaltik** [depyronick/nestjs-clickhouse#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Problems with types useFactory. All keys are optional in the config except the "httpConfig" key. This key is mandatory, but there is no information about where to get the data that needs to be placed there. There is also no information in the documentation. And the example from the documentation causes an error.

### Minimum reproduction code

https://github.com/

### Expected behavior

Need to find out where to get the data for httpConfig

### Package version

2.0.0

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [X] Linux

**Comment by depyronick** [comment]
related to: https://github.com/depyronick/clickhouse-client/blob/d61d1022878f28b07cafbe447a2cd91440e75919/src/client/interfaces/ClickHouseClientOptions.ts#L150

**Comment by depyronick** [comment]
httpConfig should not be mandatory and should be assigned defaults on construction.
will work on a fix asap
thanks for reporting

**Comment by depyronick** [comment]
> Are there any advancements?

hopefully today

**Comment by depyronick** [comment]
@ilyamixaltik sorry, having a busy week, its on my mind

**Comment by ilyamixaltik** [comment]
Nothing, I understand everything. At the moment I'm trying an older version. I hope by the time of active development you will be able to fix library
