### ISSUE TITLE
Inject multiple registerAsync clickhouse clients

### ISSUE THREAD

**Issue by stouch** [depyronick/nestjs-clickhouse#19]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It was not possible to connect multiple DI clients with async configuration.

### Describe the solution you'd like

I made a PR to solve this : https://github.com/depyronick/nestjs-clickhouse/pull/18

### Teachability, documentation, adoption, migration strategy

You then just have to set a `name` in the registerAsync to get the injected client.

### What is the motivation / use case for changing the behavior?

Multiple DI clickhouse clients.

**Comment by depyronick** [comment]
> @depyronick Do you know if you plan to keep this feature ? For now I have to use my fork to be able to inject 2 registerAsync clients.

hi. thanks for the contribution. i'll merge and release the new version asap.

**Comment by stouch** [comment]
Any news about this one ?

**Comment by depyronick** [comment]
@stouch https://github.com/depyronick/nestjs-clickhouse/releases/tag/2.0.5
