### ISSUE TITLE
Support migration database 

### ISSUE THREAD

**Issue by truonghdpk** [depyronick/nestjs-clickhouse#6]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I want to this lib have a migration data how can I do that pls, I'm searching but can see this feature is available

### Describe the solution you'd like

Does it need to use any lib to create migration I'll support and create PR for you

### Teachability, documentation, adoption, migration strategy

Yub like Typeform or other click house lib https://github.com/microfleet/clickhouse-adapter

### What is the motivation / use case for changing the behavior?

Yub easy to init database

**Comment by depyronick** [comment]
Hello, @truonghdpk!

Unfortunately this library does not support such feature. Migration features like TypeORM has are not in scope of this library. 

Maybe you could open an issue to TypeORM about your request. They can use this library to implement features like that.

**Comment by truonghdpk** [comment]
Thank you i noticed
