### ISSUE TITLE
Add ClickHouseModule.registerAsync

### ISSUE THREAD

**Issue by spiehdid** [depyronick/nestjs-clickhouse#7]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

At the moment, there is no way to do asynchronous client registration in order to transfer the config from ConfigService to it

### Describe the solution you'd like

```js
    ClickHouseModule.registerAsync({
      useFactory: (config: ConfigService) => config.get("chOptions"),
      inject: [ConfigService],
    })
```

### Teachability, documentation, adoption, migration strategy

Not necessary

### What is the motivation / use case for changing the behavior?

Not necessary

**Comment by depyronick** [comment]
Will be added as soon as possible.

**Comment by spiehdid** [comment]
@depyronick When will this feature be published?

**Comment by depyronick** [comment]
@spiehdid 

Sorry for the delay, please check the [readme](https://github.com/depyronick/nestjs-clickhouse#async-registration--async-providers) & install the new version (1.0.16)

Also please let me know if it all works as expected. If there are any problems, please open a new issue. Thanks!
