### ISSUE TITLE
Bump `@depyronick/clickhouse-client` to 2.0.0

### ISSUE THREAD

**Issue by vgorkavenko** [depyronick/nestjs-clickhouse#9]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

-

### Describe the solution you'd like

```yaml
  "dependencies": {
    "@depyronick/clickhouse-client": "^2.0.0"
  }
```

### Teachability, documentation, adoption, migration strategy

-

### What is the motivation / use case for changing the behavior?

Use features from 2.0.0

**Comment by depyronick** [comment]
hi @vgorkavenko,

will you create a pull request for that or want me to upgrade?

**Comment by vgorkavenko** [comment]
yep, I will

**Comment by vgorkavenko** [comment]
@depyronick https://github.com/depyronick/nestjs-clickhouse/pull/10

**Comment by depyronick** [comment]
@vgorkavenko thanks

https://github.com/depyronick/nestjs-clickhouse/releases/tag/2.0.0
